"""update User model

Revision ID: 7695375d1ade
Revises: 9fa9c9459ac7
Create Date: 2018-07-28 00:33:02.092255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7695375d1ade'
down_revision = '9fa9c9459ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_del_reason', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_user__username'), 'user', ['_username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user__username'), table_name='user')
    op.drop_column('user', '_del_reason')
    # ### end Alembic commands ###
