"""add models: User, Post, Comment, File, Image

Revision ID: 9fa9c9459ac7
Revises: 
Create Date: 2018-07-27 11:10:01.158328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa9c9459ac7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_username', sa.String(length=128), nullable=False),
    sa.Column('_email', sa.String(length=128), nullable=False),
    sa.Column('_password_hash', sa.String(length=128), nullable=False),
    sa.Column('_permission_level', sa.Integer(), nullable=False),
    sa.Column('reg_dt', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('_avatarS', sa.String(length=256), nullable=True),
    sa.Column('_avatar', sa.String(length=256), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('del_dt', sa.DateTime(), nullable=True),
    sa.Column('restore_dt', sa.DateTime(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('_university', sa.String(length=128), nullable=True),
    sa.Column('_city', sa.String(length=128), nullable=True),
    sa.Column('_faculty', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user__city'), 'user', ['_city'], unique=False)
    op.create_index(op.f('ix_user__email'), 'user', ['_email'], unique=True)
    op.create_index(op.f('ix_user__faculty'), 'user', ['_faculty'], unique=False)
    op.create_index(op.f('ix_user__permission_level'), 'user', ['_permission_level'], unique=False)
    op.create_index(op.f('ix_user__university'), 'user', ['_university'], unique=False)
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_name', sa.String(length=128), nullable=False),
    sa.Column('_uri', sa.String(length=64), nullable=False),
    sa.Column('_type', sa.Integer(), nullable=False),
    sa.Column('_load_count', sa.Integer(), nullable=False),
    sa.Column('_size', sa.Integer(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file__name'), 'file', ['_name'], unique=False)
    op.create_index(op.f('ix_file__uri'), 'file', ['_uri'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_title', sa.String(length=255), nullable=False),
    sa.Column('_text', sa.Text(), nullable=False),
    sa.Column('_link', sa.String(length=325), nullable=False),
    sa.Column('_watch_count', sa.Integer(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.Column('edited_dt', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post__link'), 'post', ['_link'], unique=True)
    op.create_index(op.f('ix_post__title'), 'post', ['_title'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_text', sa.Text(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.Column('edited_dt', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_uri', sa.String(length=64), nullable=False),
    sa.Column('_fmt', sa.String(length=16), nullable=False),
    sa.Column('_size', sa.Integer(), nullable=False),
    sa.Column('_load_count', sa.Integer(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image__uri'), 'image', ['_uri'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image__uri'), table_name='image')
    op.drop_table('image')
    op.drop_table('comment')
    op.drop_index(op.f('ix_post__title'), table_name='post')
    op.drop_index(op.f('ix_post__link'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_file__uri'), table_name='file')
    op.drop_index(op.f('ix_file__name'), table_name='file')
    op.drop_table('file')
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_index(op.f('ix_user__university'), table_name='user')
    op.drop_index(op.f('ix_user__permission_level'), table_name='user')
    op.drop_index(op.f('ix_user__faculty'), table_name='user')
    op.drop_index(op.f('ix_user__email'), table_name='user')
    op.drop_index(op.f('ix_user__city'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
